build:
  verbosity: detailed

clone_depth: 1

install:
  - cmd: git submodule -q update --init

environment:
  matrix:
    # /std:c++latest
    - GENERATOR: Visual Studio 15 2017 Win64
      CXXFLAGS: /std:c++latest /permissive-
      EXCEPTIONS: ON
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - GENERATOR: Visual Studio 15 2017 Win64
      CXXFLAGS: /std:c++latest /permissive-
      EXCEPTIONS: OFF
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

platform: x64

configuration:
  - Debug
  - Release

branches:
  only:
    - master

build_script:
  - mkdir build
  - cd build
  - ps: |
      if (Test-Path env:TOOLSET) {
        cmake -G "$env:GENERATOR" -T "$env:TOOLSET" -DMPARK_PATTERNS_EXCEPTIONS="$env:EXCEPTIONS" -DMPARK_PATTERNS_INCLUDE_TESTS=ON ..
      } else {
        cmake -G "$env:GENERATOR" -DMPARK_PATTERNS_EXCEPTIONS="$env:EXCEPTIONS" -DMPARK_PATTERNS_INCLUDE_TESTS=ON ..
      }
  - cmake --build . --config %CONFIGURATION%
  - ctest -V
